language: node_js
node_js:
  - '9.4.0'
install:
  - npm install
  - npm install -g truffle ganache-cli
  - truffle version

script:
- ganache-cli -p 8545 > /dev/null &
- sleep 5
- rm -rf build
- truffle compile
- truffle migrate --reset --network development
- travis_wait 30 truffle test test/drawingTests.js --compile-all --verbose-rpc